name = "PixelPerfect"
client_id = "cb0954431bbdef2e940d6f90c86dadf6"
application_url = "https://optipix.onkra.online"
embedded = true


[access_scopes]
scopes = "write_products,write_files"

[access.admin]
direct_api_mode = "online"

[auth]
redirect_urls = [
  "https://optipix.onkra.online/auth/callback",
  "https://optipix.onkra.online/auth/shopify/callback",
  "https://optipix.onkra.online/api/auth/callback"
]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]
uri = "https://optipix.onkra.online/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = [ "products/create" ]
uri = "https://optipix.onkra.online/webhooks/products/create"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
